<?php

use Arseno25\LaravelApiMagic\Commands\InstallCommand;
use Illuminate\Support\Facades\File;

uses()->group("commands", "install");

beforeEach(function () {
    $this->apiRoutesPath = base_path("routes/api.php");
    $this->bootstrapPath = base_path("bootstrap/app.php");
    $this->configPath = config_path("api-magic.php");
    $this->docsAssetPath = public_path("vendor/api-magic/docs.css");

    $this->originalApiRoutes = File::exists($this->apiRoutesPath)
        ? File::get($this->apiRoutesPath)
        : null;

    $this->originalBootstrap = File::exists($this->bootstrapPath)
        ? File::get($this->bootstrapPath)
        : null;

    $this->originalConfig = File::exists($this->configPath)
        ? File::get($this->configPath)
        : null;

    $this->originalDocsAsset = File::exists($this->docsAssetPath)
        ? File::get($this->docsAssetPath)
        : null;

    if (File::exists($this->apiRoutesPath)) {
        File::delete($this->apiRoutesPath);
    }

    if ($this->originalBootstrap !== null) {
        File::put(
            $this->bootstrapPath,
            <<<'PHP'
            <?php

            use Illuminate\Foundation\Application;
            use Illuminate\Foundation\Configuration\Exceptions;
            use Illuminate\Foundation\Configuration\Middleware;

            return Application::configure(basePath: dirname(__DIR__))
                ->withRouting(
                    web: __DIR__.'/../routes/web.php',
                    commands: __DIR__.'/../routes/console.php',
                    health: '/up',
                )
                ->withMiddleware(function (Middleware $middleware): void {
                    //
                })
                ->withExceptions(function (Exceptions $exceptions): void {
                    //
                })->create();
            PHP
            ,
        );
    }

    if (File::exists($this->configPath)) {
        File::delete($this->configPath);
    }

    if (File::exists($this->docsAssetPath)) {
        File::delete($this->docsAssetPath);
    }
});

afterEach(function () {
    if ($this->originalApiRoutes === null) {
        File::delete($this->apiRoutesPath);
    } else {
        File::put($this->apiRoutesPath, $this->originalApiRoutes);
    }

    if ($this->originalBootstrap !== null) {
        File::put($this->bootstrapPath, $this->originalBootstrap);
    }

    if ($this->originalConfig === null) {
        if (File::exists($this->configPath)) {
            File::delete($this->configPath);
        }
    } else {
        File::put($this->configPath, $this->originalConfig);
    }

    if ($this->originalDocsAsset === null) {
        if (File::exists($this->docsAssetPath)) {
            File::delete($this->docsAssetPath);
        }
    } else {
        File::ensureDirectoryExists(dirname($this->docsAssetPath));
        File::put($this->docsAssetPath, $this->originalDocsAsset);
    }
});

it("has the correct command name", function () {
    $command = app(InstallCommand::class);

    expect($command->getName())->toBe("api-magic:install");
});

it("creates the api routes file and publishes the config", function () {
    $this->artisan("api-magic:install")->assertExitCode(0);

    expect(File::exists($this->apiRoutesPath))->toBeTrue();
    expect(File::get($this->apiRoutesPath))->toContain("API Routes");
    expect(File::get($this->apiRoutesPath))->toContain(
        "Generated by api-magic:install",
    );
    expect(File::exists($this->configPath))->toBeTrue();
});

it("updates bootstrap app to load api routes", function () {
    $this->artisan("api-magic:install")->assertExitCode(0);

    expect(File::get($this->bootstrapPath))->toContain(
        "api: __DIR__.'/../routes/api.php',",
    );
});

it("publishes the local docs assets by default", function () {
    $this->artisan("api-magic:install")->assertExitCode(0);

    expect(File::exists($this->docsAssetPath))->toBeTrue();
});

it("can skip publishing the local docs assets", function () {
    $this->artisan("api-magic:install --without-assets")->assertExitCode(0);

    expect(File::exists($this->docsAssetPath))->toBeFalse();
});

it("does not overwrite custom api routes even with force enabled", function () {
    File::ensureDirectoryExists(dirname($this->apiRoutesPath));
    File::put(
        $this->apiRoutesPath,
        <<<'PHP'
        <?php

        use Illuminate\Support\Facades\Route;

        Route::get('/custom', fn () => response()->json(['ok' => true]));
        PHP
        ,
    );

    $this->artisan("api-magic:install --force")->assertExitCode(0);

    expect(File::get($this->apiRoutesPath))->toContain("Route::get('/custom'");
    expect(File::get($this->apiRoutesPath))->not->toContain(
        "Generated by api-magic:install",
    );
});
