<?php

use Arseno25\LaravelApiMagic\Generators\TypescriptGenerator;

uses()->group('generators', 'typescript');

beforeEach(function () {
    $this->generator = new TypescriptGenerator;
});

describe('TypeScript interface generation', function () {
    it('generates a valid TypeScript namespace', function () {
        $schema = [
            'generated_at' => '2026-01-01T00:00:00Z',
            'endpoints' => [],
        ];

        $output = $this->generator->generate($schema, 'ApiTypes');

        expect($output)->toContain('declare namespace ApiTypes');
        expect($output)->toContain('Auto-generated by Laravel API Magic');
    });

    it('generates request interfaces for POST endpoints', function () {
        $schema = [
            'generated_at' => '2026-01-01T00:00:00Z',
            'endpoints' => [
                '/api/products' => [
                    'post' => [
                        'method' => 'post',
                        'path' => '/api/products',
                        'summary' => 'Create Product',
                        'parameters' => [
                            'body' => [
                                ['name' => 'title', 'type' => 'string', 'rules' => 'required|string|max:255'],
                                ['name' => 'price', 'type' => 'number', 'rules' => 'required|numeric'],
                                ['name' => 'is_active', 'type' => 'boolean', 'rules' => 'sometimes|boolean'],
                            ],
                            'path' => [],
                            'query' => [],
                        ],
                        'security' => [],
                        'tags' => ['Products'],
                    ],
                ],
            ],
        ];

        $output = $this->generator->generate($schema);

        expect($output)->toContain('interface PostApiProductsRequest');
        expect($output)->toContain('title: string;');
        expect($output)->toContain('price: number;');
        expect($output)->toContain('is_active?: boolean;');
    });

    it('generates query interfaces for GET endpoints', function () {
        $schema = [
            'generated_at' => '2026-01-01T00:00:00Z',
            'endpoints' => [
                '/api/products' => [
                    'get' => [
                        'method' => 'get',
                        'path' => '/api/products',
                        'summary' => 'List Products',
                        'parameters' => [
                            'body' => [],
                            'path' => [],
                            'query' => [
                                ['name' => 'page', 'type' => 'integer'],
                                ['name' => 'per_page', 'type' => 'integer'],
                                ['name' => 'search', 'type' => 'string'],
                            ],
                        ],
                        'security' => [],
                        'tags' => ['Products'],
                    ],
                ],
            ],
        ];

        $output = $this->generator->generate($schema);

        expect($output)->toContain('interface GetApiProductsQuery');
        expect($output)->toContain('page?: number;');
        expect($output)->toContain('per_page?: number;');
        expect($output)->toContain('search?: string;');
    });

    it('generates path params interfaces', function () {
        $schema = [
            'generated_at' => '2026-01-01T00:00:00Z',
            'endpoints' => [
                '/api/products/{id}' => [
                    'get' => [
                        'method' => 'get',
                        'path' => '/api/products/{id}',
                        'summary' => 'Show Product',
                        'parameters' => [
                            'body' => [],
                            'path' => [
                                ['name' => 'id', 'type' => 'integer'],
                            ],
                            'query' => [],
                        ],
                        'security' => [],
                        'tags' => ['Products'],
                    ],
                ],
            ],
        ];

        $output = $this->generator->generate($schema);

        expect($output)->toContain('interface GetApiProductsParams');
        expect($output)->toContain('id: number;');
    });

    it('generates response interfaces with pagination for GET', function () {
        $schema = [
            'generated_at' => '2026-01-01T00:00:00Z',
            'endpoints' => [
                '/api/products' => [
                    'get' => [
                        'method' => 'get',
                        'path' => '/api/products',
                        'summary' => 'List Products',
                        'parameters' => ['body' => [], 'path' => [], 'query' => []],
                        'security' => [],
                        'tags' => ['Products'],
                    ],
                ],
            ],
        ];

        $output = $this->generator->generate($schema);

        expect($output)->toContain('interface GetApiProductsResponse');
        expect($output)->toContain('meta?:');
        expect($output)->toContain('current_page: number;');
        expect($output)->toContain('total: number;');
    });

    it('maps enum fields to union types', function () {
        $schema = [
            'generated_at' => '2026-01-01T00:00:00Z',
            'endpoints' => [
                '/api/products' => [
                    'post' => [
                        'method' => 'post',
                        'path' => '/api/products',
                        'summary' => 'Create Product',
                        'parameters' => [
                            'body' => [
                                ['name' => 'status', 'type' => 'string', 'enum' => ['active', 'draft', 'archived'], 'rules' => 'required'],
                            ],
                            'path' => [],
                            'query' => [],
                        ],
                        'security' => [],
                        'tags' => ['Products'],
                    ],
                ],
            ],
        ];

        $output = $this->generator->generate($schema);

        expect($output)->toContain("'active' | 'draft' | 'archived'");
    });

    it('maps file upload fields to File | Blob', function () {
        $schema = [
            'generated_at' => '2026-01-01T00:00:00Z',
            'endpoints' => [
                '/api/products' => [
                    'post' => [
                        'method' => 'post',
                        'path' => '/api/products',
                        'summary' => 'Create Product',
                        'parameters' => [
                            'body' => [
                                ['name' => 'image', 'type' => 'file', 'is_file' => true, 'rules' => 'required'],
                            ],
                            'path' => [],
                            'query' => [],
                        ],
                        'security' => [],
                        'tags' => ['Products'],
                    ],
                ],
            ],
        ];

        $output = $this->generator->generate($schema);

        expect($output)->toContain('File | Blob');
    });

    it('generates ApiRoutes type map', function () {
        $schema = [
            'generated_at' => '2026-01-01T00:00:00Z',
            'endpoints' => [
                '/api/products' => [
                    'get' => [
                        'method' => 'get',
                        'path' => '/api/products',
                        'summary' => 'List',
                        'parameters' => ['body' => [], 'path' => [], 'query' => []],
                        'security' => [],
                        'tags' => ['Products'],
                    ],
                ],
            ],
        ];

        $output = $this->generator->generate($schema);

        expect($output)->toContain('interface ApiRoutes');
        expect($output)->toContain("'GET /api/products'");
    });

    it('uses custom namespace', function () {
        $schema = [
            'generated_at' => '2026-01-01T00:00:00Z',
            'endpoints' => [],
        ];

        $output = $this->generator->generate($schema, 'MyApi');

        expect($output)->toContain('declare namespace MyApi');
    });
});
