<?php

namespace Arseno25\LaravelApiMagic\Generators;

use Illuminate\Support\Str;

final class TypescriptGenerator
{
    /**
     * Generate TypeScript interfaces from the internal API schema.
     *
     * @param  array<string, mixed>  $schema
     */
    public function generate(
        array $schema,
        string $namespace = "ApiTypes",
    ): string {
        $generatedAt = $schema["generated_at"] ?? "unknown";
        $output = "// Auto-generated by Laravel API Magic\n";
        $output .= "// Generated at: {$generatedAt}\n";
        $output .=
            "// Do not edit manually — re-run `php artisan api-magic:ts` to regenerate.\n\n";
        $output .= "declare namespace {$namespace} {\n\n";

        $interfaces = [];
        $routeTypes = [];

        foreach ($schema["endpoints"] ?? [] as $path => $methods) {
            foreach ($methods as $method => $endpoint) {
                $interfaceName = $this->generateInterfaceName($method, $path);

                // Request interface (from body params)
                if (!empty($endpoint["parameters"]["body"])) {
                    $requestInterface = $this->buildInterface(
                        $interfaceName . "Request",
                        $endpoint["parameters"]["body"],
                        $method,
                    );
                    $interfaces[] = $requestInterface;
                }

                // Request query interface (from query params)
                if (!empty($endpoint["parameters"]["query"])) {
                    $queryInterface = $this->buildQueryInterface(
                        $interfaceName . "Query",
                        $endpoint["parameters"]["query"],
                    );
                    $interfaces[] = $queryInterface;
                }

                // Path params interface
                if (!empty($endpoint["parameters"]["path"])) {
                    $pathInterface = $this->buildPathInterface(
                        $interfaceName . "Params",
                        $endpoint["parameters"]["path"],
                    );
                    $interfaces[] = $pathInterface;
                }

                // Response interface (generic or from resource)
                $responseInterface = $this->buildResponseInterface(
                    $interfaceName . "Response",
                    $endpoint,
                );
                $interfaces[] = $responseInterface;

                // Collect route type mapping
                $routeTypes[] = $this->buildRouteType(
                    $method,
                    $path,
                    $interfaceName,
                    $endpoint,
                );
            }
        }

        foreach ($interfaces as $interface) {
            $output .= $this->indent($interface, 1) . "\n\n";
        }

        // Add API routes type map
        $output .=
            $this->indent($this->buildApiRoutesType($routeTypes), 1) . "\n\n";

        $output .= "}\n";

        return $output;
    }

    /**
     * Generate a full TypeScript API client SDK.
     *
     * @param  array<string, mixed>  $schema
     */
    public function generateSdk(array $schema, string $baseUrl = ""): string
    {
        $generatedAt = $schema["generated_at"] ?? "unknown";
        $output = "// Auto-generated API Client by Laravel API Magic\n";
        $output .= "// Generated at: {$generatedAt}\n";
        $output .=
            "// Do not edit manually — re-run `php artisan api-magic:ts --sdk` to regenerate.\n\n";

        // ApiClient class
        $output .= "export interface ApiConfig {\n";
        $output .= "  baseUrl: string;\n";
        $output .= "  token?: string;\n";
        $output .= "  headers?: Record<string, string>;\n";
        $output .= "}\n\n";

        $output .= "export class ApiClient {\n";
        $output .= "  private config: ApiConfig;\n\n";
        $output .= "  constructor(config: ApiConfig) {\n";
        $output .= "    this.config = config;\n";
        $output .= "  }\n\n";

        $output .=
            "  private async request<T>(method: string, path: string, data?: any, params?: Record<string, any>): Promise<T> {\n";
        $output .= "    const url = new URL(path, this.config.baseUrl);\n";
        $output .= "    if (params) {\n";
        $output .= "      Object.entries(params).forEach(([key, value]) => {\n";
        $output .=
            "        if (value !== undefined && value !== null) url.searchParams.set(key, String(value));\n";
        $output .= "      });\n";
        $output .= "    }\n\n";
        $output .= "    const headers: Record<string, string> = {\n";
        $output .= "      'Accept': 'application/json',\n";
        $output .= "      'Content-Type': 'application/json',\n";
        $output .= "      ...this.config.headers,\n";
        $output .= "    };\n\n";
        $output .= "    if (this.config.token) {\n";
        $output .=
            "      headers['Authorization'] = `Bearer \${this.config.token}`;\n";
        $output .= "    }\n\n";
        $output .= "    const response = await fetch(url.toString(), {\n";
        $output .= "      method: method.toUpperCase(),\n";
        $output .= "      headers,\n";
        $output .= "      body: data ? JSON.stringify(data) : undefined,\n";
        $output .= "    });\n\n";
        $output .= "    if (!response.ok) {\n";
        $output .=
            "      throw new Error(`API Error: \${response.status} \${response.statusText}`);\n";
        $output .= "    }\n\n";
        $output .= "    return response.json();\n";
        $output .= "  }\n\n";

        // Generate typed methods
        foreach ($schema["endpoints"] ?? [] as $path => $methods) {
            foreach ($methods as $method => $endpoint) {
                $methodName = $this->generateMethodName($method, $path);
                $interfaceName = $this->generateInterfaceName($method, $path);

                $hasBody = !empty($endpoint["parameters"]["body"]);
                $hasQuery = !empty($endpoint["parameters"]["query"]);
                $hasPath = !empty($endpoint["parameters"]["path"]);
                $deprecated = $endpoint["deprecated"] ?? false;

                $params = [];
                if ($hasPath) {
                    $params[] = "params: {$interfaceName}Params";
                }
                if ($hasBody) {
                    $params[] = "data: {$interfaceName}Request";
                }
                if ($hasQuery) {
                    $params[] = "query?: {$interfaceName}Query";
                }

                $paramStr = implode(", ", $params);

                if ($deprecated) {
                    $output .=
                        "  /** @deprecated " .
                        ($endpoint["deprecated_info"]["message"] ?? "") .
                        " */\n";
                }

                $output .= "  async {$methodName}({$paramStr}): Promise<{$interfaceName}Response> {\n";

                // Build the path with interpolation
                $pathExpr = $this->buildPathExpression($path, $hasPath);
                $dataArg = $hasBody ? "data" : "undefined";
                $queryArg = $hasQuery ? "query" : "undefined";

                $output .= "    return this.request<{$interfaceName}Response>('{$method}', {$pathExpr}, {$dataArg}, {$queryArg});\n";
                $output .= "  }\n\n";
            }
        }

        $output .= "}\n\n";

        // Create default factory
        $output .=
            "export function createApiClient(baseUrl: string, token?: string): ApiClient {\n";
        $output .= "  return new ApiClient({ baseUrl, token });\n";
        $output .= "}\n";

        return $output;
    }

    /**
     * Generate a camelCase method name from HTTP method and path.
     */
    private function generateMethodName(string $method, string $path): string
    {
        $segments = array_filter(
            explode("/", $path),
            fn($s) => $s && !str_starts_with($s, "{") && $s !== "api",
        );

        $name = match ($method) {
            "get" => "get",
            "post" => "create",
            "put", "patch" => "update",
            "delete" => "delete",
            default => $method,
        };

        foreach ($segments as $segment) {
            $name .= Str::studly($segment);
        }

        return $name;
    }

    /**
     * Build a path expression for TypeScript template literals.
     */
    private function buildPathExpression(string $path, bool $hasParams): string
    {
        if (!$hasParams) {
            return "'{$path}'";
        }

        $expr = preg_replace("/\{(\w+)\}/", '\${params.$1}', $path);

        return "`{$expr}`";
    }

    /**
     * Generate an interface name from method and path.
     */
    private function generateInterfaceName(string $method, string $path): string
    {
        $segments = explode("/", trim($path, "/"));
        $parts = [];

        foreach ($segments as $segment) {
            if (str_starts_with($segment, "{")) {
                continue; // Skip path parameters
            }
            // Remove version prefix like v1, v2
            if (preg_match('/^v\d+$/', $segment)) {
                continue;
            }
            $parts[] = Str::studly($segment);
        }

        $name = implode("", $parts);
        $methodPrefix = Str::studly($method);

        return $methodPrefix . $name;
    }

    /**
     * Build a TypeScript interface from request body fields.
     *
     * @param  array<int|string, mixed>  $fields
     */
    private function buildInterface(
        string $name,
        array $fields,
        string $method,
    ): string {
        $lines = ["interface {$name} {"];

        foreach ($fields as $key => $field) {
            // Because body fields are structured as an associative array [$fieldName => $properties]
            // but query/path properties are sequential arrays [['name' => 'foo']], we resolve correctly:
            if (!is_array($field)) {
                continue;
            }
            $fieldName = is_string($key) ? $key : $field["name"] ?? "unknown";
            $tsType = $this->mapToTsType($field["type"] ?? "string", $field);
            $optional = $this->isOptional($field, $method) ? "?" : "";
            $comment = $this->buildFieldComment($field);

            if ($comment) {
                $lines[] = "  /** {$comment} */";
            }
            $lines[] = "  {$fieldName}{$optional}: {$tsType};";
        }

        $lines[] = "}";

        return implode("\n", $lines);
    }

    /**
     * Build a TypeScript interface for query parameters.
     *
     * @param  array<int, array<string, mixed>>  $params
     */
    private function buildQueryInterface(string $name, array $params): string
    {
        $lines = ["interface {$name} {"];

        foreach ($params as $param) {
            $paramName = $param["name"] ?? "unknown";
            $tsType = $this->mapToTsType($param["type"] ?? "string", $param);
            $lines[] = "  {$paramName}?: {$tsType};";
        }

        $lines[] = "}";

        return implode("\n", $lines);
    }

    /**
     * Build a TypeScript interface for path parameters.
     *
     * @param  array<int, array<string, mixed>>  $params
     */
    private function buildPathInterface(string $name, array $params): string
    {
        $lines = ["interface {$name} {"];

        foreach ($params as $param) {
            $paramName = $param["name"] ?? "unknown";
            $tsType =
                ($param["type"] ?? "string") === "integer"
                    ? "number"
                    : "string";
            $lines[] = "  {$paramName}: {$tsType};";
        }

        $lines[] = "}";

        return implode("\n", $lines);
    }

    /**
     * Build a generic response interface.
     *
     * @param  array<string, mixed>  $endpoint
     */
    private function buildResponseInterface(
        string $name,
        array $endpoint,
    ): string {
        $lines = ["interface {$name} {"];
        $lines[] =
            "  data: Record<string, unknown> | Record<string, unknown>[];";

        if (in_array(strtolower($endpoint["method"] ?? ""), ["get"])) {
            $lines[] = "  meta?: {";
            $lines[] = "    current_page: number;";
            $lines[] = "    last_page: number;";
            $lines[] = "    per_page: number;";
            $lines[] = "    total: number;";
            $lines[] = "  };";
            $lines[] = "  links?: {";
            $lines[] = "    first: string | null;";
            $lines[] = "    last: string | null;";
            $lines[] = "    prev: string | null;";
            $lines[] = "    next: string | null;";
            $lines[] = "  };";
        }

        $lines[] = "}";

        return implode("\n", $lines);
    }

    /**
     * Build route type entry.
     *
     * @param  array<string, mixed>  $endpoint
     * @return array<string, string>
     */
    private function buildRouteType(
        string $method,
        string $path,
        string $interfaceName,
        array $endpoint,
    ): array {
        $entry = [
            "method" => strtoupper($method),
            "path" => $path,
        ];

        if (!empty($endpoint["parameters"]["body"])) {
            $entry["request"] = $interfaceName . "Request";
        }
        if (!empty($endpoint["parameters"]["query"])) {
            $entry["query"] = $interfaceName . "Query";
        }
        if (!empty($endpoint["parameters"]["path"])) {
            $entry["params"] = $interfaceName . "Params";
        }
        $entry["response"] = $interfaceName . "Response";

        return $entry;
    }

    /**
     * Build the ApiRoutes type map.
     *
     * @param  array<int, array<string, string>>  $routeTypes
     */
    private function buildApiRoutesType(array $routeTypes): string
    {
        $lines = ["interface ApiRoutes {"];

        foreach ($routeTypes as $route) {
            $method = $route["method"];
            $path = $route["path"];
            $key = "{$method} {$path}";

            $members = [];
            if (isset($route["request"])) {
                $members[] = "request: {$route["request"]}";
            }
            if (isset($route["query"])) {
                $members[] = "query: {$route["query"]}";
            }
            if (isset($route["params"])) {
                $members[] = "params: {$route["params"]}";
            }
            $members[] = "response: {$route["response"]}";

            $lines[] = "  '{$key}': { " . implode("; ", $members) . " };";
        }

        $lines[] = "}";

        return implode("\n", $lines);
    }

    /**
     * Map a PHP/OpenAPI type to a TypeScript type.
     *
     * @param  array<string, mixed>  $field
     */
    private function mapToTsType(string $type, array $field = []): string
    {
        // Handle enums
        if (!empty($field["enum"])) {
            $enumValues = array_map(fn($v) => "'{$v}'", $field["enum"]);

            return implode(" | ", $enumValues);
        }

        // Handle file uploads
        if (!empty($field["is_file"])) {
            return "File | Blob";
        }

        return match ($type) {
            "integer",
            "int",
            "bigint",
            "number",
            "float",
            "double",
            "decimal"
                => "number",
            "boolean", "bool" => "boolean",
            "array" => "unknown[]",
            "object", "json" => "Record<string, unknown>",
            "date", "datetime", "timestamp" => "string",
            "file", "image" => "File | Blob",
            default => "string",
        };
    }

    /**
     * Check if a field is optional.
     *
     * @param  array<string, mixed>  $field
     */
    private function isOptional(array $field, string $method): bool
    {
        $rules = $field["rules"] ?? "";
        if (is_array($rules)) {
            $rules = implode("|", $rules);
        }

        if (
            str_contains($rules, "sometimes") ||
            str_contains($rules, "nullable")
        ) {
            return true;
        }

        // PATCH/PUT requests often have optional fields
        if (
            in_array($method, ["patch", "put"]) &&
            !str_contains($rules, "required")
        ) {
            return true;
        }

        return false;
    }

    /**
     * Build a JSDoc comment for a field.
     *
     * @param  array<string, mixed>  $field
     */
    private function buildFieldComment(array $field): string
    {
        $parts = [];

        if (!empty($field["type"])) {
            $parts[] = "Type: {$field["type"]}";
        }
        if (!empty($field["enum"])) {
            $parts[] = "Enum: " . implode(", ", $field["enum"]);
        }
        if (!empty($field["rules"])) {
            $rules = is_array($field["rules"])
                ? implode("|", $field["rules"])
                : $field["rules"];
            $parts[] = "Rules: {$rules}";
        }

        return implode(" | ", $parts);
    }

    /**
     * Indent a block of text.
     */
    private function indent(string $text, int $level): string
    {
        $indent = str_repeat("  ", $level);

        return $indent . str_replace("\n", "\n" . $indent, $text);
    }
}
