<?php

namespace Arseno25\LaravelApiMagic\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use RuntimeException;

final class InstallCommand extends Command
{
    private const API_ROUTES_MARKER = '// Generated by api-magic:install';

    protected $signature = 'api-magic:install
        {--force : Overwrite generated setup files when possible}
        {--stubs : Also publish the package stubs}
        {--without-assets : Skip publishing the bundled local docs assets}';

    protected $description = 'Install the package into an application by preparing API routes and publishing configuration';

    public function handle(): int
    {
        try {
            $routesStatus = $this->ensureApiRoutesFile();
            $bootstrapStatus = $this->ensureBootstrapUsesApiRoutes();

            $this->publishTag('api-magic-config', 'Configuration published.');

            if ($this->option('stubs')) {
                $this->publishTag('api-magic-stubs', 'Stubs published.');
            }

            if (! $this->option('without-assets')) {
                $this->publishTag(
                    'api-magic-assets',
                    'Local docs assets published.',
                );
            }
        } catch (RuntimeException $exception) {
            $this->error($exception->getMessage());

            return self::FAILURE;
        }

        if ($routesStatus === 'created') {
            $this->info('Created routes/api.php.');
        } elseif ($routesStatus === 'existing') {
            $this->line('routes/api.php already exists.');
        } else {
            $this->warn(
                'routes/api.php was not overwritten because it does not match the installer scaffold.',
            );
        }

        if ($bootstrapStatus === 'updated') {
            $this->info('Updated bootstrap/app.php to load API routes.');
        } else {
            $this->line('bootstrap/app.php already loads API routes.');
        }

        $this->newLine();
        $this->line('Next steps:');
        $this->line('1. Add your generated routes to routes/api.php.');
        $this->line(
            '2. Run `php artisan route:list --path=api` to verify the API routes are loaded.',
        );
        $this->line(
            '3. Docs UI assets are published to `public/vendor/api-magic` by default.',
        );

        return self::SUCCESS;
    }

    private function ensureApiRoutesFile(): string
    {
        $apiRoutesPath = base_path('routes/api.php');

        if (File::exists($apiRoutesPath)) {
            if (! $this->option('force')) {
                return 'existing';
            }

            $existingContent = File::get($apiRoutesPath);
            if (! $this->isInstallerManagedApiRoutes($existingContent)) {
                return 'skipped';
            }
        }

        File::ensureDirectoryExists(dirname($apiRoutesPath));

        $written = File::put(
            $apiRoutesPath,
            <<<'PHP'
            <?php

            use Illuminate\Support\Facades\Route;

            // Generated by api-magic:install

            /*
            |--------------------------------------------------------------------------
            | API Routes
            |--------------------------------------------------------------------------
            |
            | Here is where you may register API routes for your application.
            |
            */
            PHP
            ,
        );

        if ($written === false) {
            throw new RuntimeException('Unable to write routes/api.php.');
        }

        return 'created';
    }

    private function ensureBootstrapUsesApiRoutes(): string
    {
        $bootstrapPath = base_path('bootstrap/app.php');

        if (! File::exists($bootstrapPath)) {
            throw new RuntimeException('bootstrap/app.php was not found.');
        }

        $content = File::get($bootstrapPath);
        $apiRoutesLine = "        api: __DIR__.'/../routes/api.php',";

        if (str_contains($content, 'routes/api.php')) {
            return 'existing';
        }

        $updatedContent = $this->injectApiRoutesLine($content, $apiRoutesLine);

        if ($updatedContent === null) {
            throw new RuntimeException(
                'Unable to update bootstrap/app.php automatically.',
            );
        }

        $written = File::put($bootstrapPath, $updatedContent);
        if ($written === false) {
            throw new RuntimeException('Unable to write bootstrap/app.php.');
        }

        return 'updated';
    }

    private function injectApiRoutesLine(
        string $content,
        string $apiRoutesLine,
    ): ?string {
        $webRoutesLine = "        web: __DIR__.'/../routes/web.php',";
        if (str_contains($content, $webRoutesLine)) {
            return str_replace(
                $webRoutesLine,
                $webRoutesLine."\n".$apiRoutesLine,
                $content,
            );
        }

        $commandsRoutesLine =
            "        commands: __DIR__.'/../routes/console.php',";
        if (str_contains($content, $commandsRoutesLine)) {
            return str_replace(
                $commandsRoutesLine,
                $apiRoutesLine."\n".$commandsRoutesLine,
                $content,
            );
        }

        return null;
    }

    private function publishTag(string $tag, string $message): void
    {
        $exitCode = $this->call('vendor:publish', [
            '--tag' => $tag,
            '--force' => $this->option('force'),
        ]);
        if ($exitCode !== self::SUCCESS) {
            throw new RuntimeException(
                "Publishing vendor assets for tag [{$tag}] failed.",
            );
        }

        $this->line($message);
    }

    private function isInstallerManagedApiRoutes(string $content): bool
    {
        return str_contains($content, self::API_ROUTES_MARKER);
    }
}
