<?php

namespace Arseno25\LaravelApiMagic\Exporters;

use Illuminate\Support\Str;

final class InsomniaExporter
{
    /**
     * Convert the internal API schema to an Insomnia v4 export format.
     *
     * @param  array<string, mixed>  $schema
     * @return array<string, mixed>
     */
    public function export(array $schema, string $baseUrl): array
    {
        $resources = [];
        $workspaceId = 'wrk_'.Str::random(24);
        $envId = 'env_'.Str::random(24);

        // Workspace
        $resources[] = [
            '_id' => $workspaceId,
            '_type' => 'workspace',
            'name' => $schema['title'] ?? 'API Documentation',
            'description' => 'Auto-generated by Laravel API Magic',
            'scope' => 'collection',
        ];

        // Base environment
        $resources[] = [
            '_id' => $envId,
            '_type' => 'environment',
            'parentId' => $workspaceId,
            'name' => 'Base Environment',
            'data' => [
                'base_url' => $baseUrl,
                'token' => '',
            ],
        ];

        // Create folders by tag/group
        $folderMap = [];
        /** @var array<string, array<string, array<string, mixed>>> $endpoints */
        $endpoints = $schema['endpoints'] ?? [];

        foreach ($endpoints as $path => $methods) {
            foreach ($methods as $method => $endpoint) {
                $tags = $endpoint['tags'] ?? ['Default'];
                $tag = $tags[0] ?? 'Default';

                if (! isset($folderMap[$tag])) {
                    $folderId = 'fld_'.Str::random(24);
                    $folderMap[$tag] = $folderId;
                    $resources[] = [
                        '_id' => $folderId,
                        '_type' => 'request_group',
                        'parentId' => $workspaceId,
                        'name' => $tag,
                        'description' => "Operations related to {$tag}",
                    ];
                }

                $resources[] = $this->buildRequest(
                    $method,
                    $path,
                    $endpoint,
                    $baseUrl,
                    $folderMap[$tag]
                );
            }
        }

        return [
            '_type' => 'export',
            '__export_format' => 4,
            '__export_date' => now()->toIso8601String(),
            '__export_source' => 'laravel-api-magic',
            'resources' => $resources,
        ];
    }

    /**
     * Build a single Insomnia request resource.
     *
     * @param  array<string, mixed>  $endpoint
     * @return array<string, mixed>
     */
    private function buildRequest(string $method, string $path, array $endpoint, string $baseUrl, string $parentId): array
    {
        $requestId = 'req_'.Str::random(24);

        $request = [
            '_id' => $requestId,
            '_type' => 'request',
            'parentId' => $parentId,
            'name' => $endpoint['summary'] ?? strtoupper($method).' '.$path,
            'description' => $endpoint['description'] ?? '',
            'method' => strtoupper($method),
            'url' => '{{ _.base_url }}'.$path,
            'headers' => $this->buildHeaders($endpoint),
            'parameters' => $this->buildQueryParams($endpoint),
            'authentication' => $this->buildAuth($endpoint),
        ];

        // Add body for methods that support it
        if (in_array(strtoupper($method), ['POST', 'PUT', 'PATCH'])) {
            $request['body'] = $this->buildBody($endpoint);
        }

        return $request;
    }

    /**
     * Build request headers.
     *
     * @param  array<string, mixed>  $endpoint
     * @return array<int, array<string, mixed>>
     */
    private function buildHeaders(array $endpoint): array
    {
        $headers = [
            ['name' => 'Accept', 'value' => 'application/json'],
        ];

        $method = strtoupper((string) ($endpoint['method'] ?? 'GET'));
        if (in_array($method, ['POST', 'PUT', 'PATCH'])) {
            $hasFile = false;
            $bodyFields = $endpoint['parameters']['body'] ?? [];
            if (is_array($bodyFields)) {
                foreach ($bodyFields as $field) {
                    if (is_array($field) && ($field['is_file'] ?? false)) {
                        $hasFile = true;
                        break;
                    }
                }
            }

            if (! $hasFile) {
                $headers[] = ['name' => 'Content-Type', 'value' => 'application/json'];
            }
        }

        return $headers;
    }

    /**
     * Build query parameters.
     *
     * @param  array<string, mixed>  $endpoint
     * @return array<int, array<string, mixed>>
     */
    private function buildQueryParams(array $endpoint): array
    {
        $params = [];
        $queryParams = $endpoint['parameters']['query'] ?? [];

        if (is_array($queryParams)) {
            foreach ($queryParams as $param) {
                if (! is_array($param)) {
                    continue;
                }
                $params[] = [
                    'name' => $param['name'] ?? '',
                    'value' => '',
                    'disabled' => ! ($param['required'] ?? false),
                    'description' => $param['description'] ?? '',
                ];
            }
        }

        return $params;
    }

    /**
     * Build authentication config.
     *
     * @param  array<string, mixed>  $endpoint
     * @return array<string, mixed>
     */
    private function buildAuth(array $endpoint): array
    {
        $security = $endpoint['security'] ?? [];

        if (! empty($security)) {
            return [
                'type' => 'bearer',
                'token' => '{{ _.token }}',
                'prefix' => 'Bearer',
            ];
        }

        return ['type' => 'none'];
    }

    /**
     * Build the request body.
     *
     * @param  array<string, mixed>  $endpoint
     * @return array<string, mixed>
     */
    private function buildBody(array $endpoint): array
    {
        $bodyFields = $endpoint['parameters']['body'] ?? [];

        if (empty($bodyFields) || ! is_array($bodyFields)) {
            return ['mimeType' => '', 'text' => ''];
        }

        $hasFile = false;
        foreach ($bodyFields as $field) {
            if (is_array($field) && ($field['is_file'] ?? false)) {
                $hasFile = true;
                break;
            }
        }

        if ($hasFile) {
            return $this->buildMultipartBody($bodyFields);
        }

        return $this->buildJsonBody($bodyFields);
    }

    /**
     * Build JSON body.
     *
     * @param  array<string, mixed>  $fields
     * @return array<string, mixed>
     */
    private function buildJsonBody(array $fields): array
    {
        $data = [];
        foreach ($fields as $name => $field) {
            if (! is_array($field)) {
                continue;
            }
            $data[(string) $name] = $this->getExampleValue($field);
        }

        return [
            'mimeType' => 'application/json',
            'text' => json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES),
        ];
    }

    /**
     * Build multipart body.
     *
     * @param  array<string, mixed>  $fields
     * @return array<string, mixed>
     */
    private function buildMultipartBody(array $fields): array
    {
        $params = [];
        foreach ($fields as $name => $field) {
            if (! is_array($field)) {
                continue;
            }
            $isFile = $field['is_file'] ?? false;
            $params[] = [
                'name' => (string) $name,
                'value' => $isFile ? '' : (string) $this->getExampleValue($field),
                'type' => $isFile ? 'file' : 'text',
                'fileName' => $isFile ? '' : null,
            ];
        }

        return [
            'mimeType' => 'multipart/form-data',
            'params' => $params,
        ];
    }

    /**
     * Get example value for a field.
     *
     * @param  array<string, mixed>  $field
     */
    private function getExampleValue(array $field): string|int|bool|float
    {
        $type = strtolower((string) ($field['type'] ?? 'string'));
        $name = strtolower((string) ($field['name'] ?? ''));

        return match (true) {
            $type === 'integer' || $type === 'int' => 1,
            $type === 'number' || $type === 'float' || $type === 'double' || $type === 'decimal' => 9.99,
            $type === 'boolean' || $type === 'bool' => true,
            str_contains($name, 'email') => 'user@example.com',
            str_contains($name, 'name') => 'Example Name',
            str_contains($name, 'url') || str_contains($name, 'link') => 'https://example.com',
            str_contains($name, 'phone') => '+1234567890',
            default => 'string',
        };
    }
}
