<?php

namespace Arseno25\LaravelApiMagic\Exporters;

use Illuminate\Support\Str;

final class PostmanExporter
{
    /**
     * Convert the internal API schema to a Postman Collection v2.1 format.
     *
     * @param  array<string, mixed>  $schema
     * @return array<string, mixed>
     */
    public function export(array $schema, string $baseUrl): array
    {
        $collection = [
            'info' => [
                '_postman_id' => Str::uuid()->toString(),
                'name' => $schema['title'] ?? 'API Documentation',
                'description' => 'Auto-generated by Laravel API Magic v'.
                    ($schema['version'] ?? '1.0.0'),
                'schema' => 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
            ],
            'variable' => [
                [
                    'key' => 'base_url',
                    'value' => rtrim($baseUrl, '/'),
                    'type' => 'string',
                ],
                [
                    'key' => 'token',
                    'value' => '',
                    'type' => 'string',
                ],
            ],
            'auth' => [
                'type' => 'bearer',
                'bearer' => [
                    [
                        'key' => 'token',
                        'value' => '{{token}}',
                        'type' => 'string',
                    ],
                ],
            ],
            'item' => [],
        ];

        // Group endpoints into folders
        $folders = [];

        foreach ($schema['endpoints'] ?? [] as $path => $methods) {
            foreach ($methods as $method => $endpoint) {
                $tags = $endpoint['tags'] ?? ['General'];
                $folder = $tags[0] ?? 'General';

                if (! isset($folders[$folder])) {
                    $folders[$folder] = [];
                }

                $folders[$folder][] = $this->buildRequest(
                    $method,
                    $path,
                    $endpoint,
                    $baseUrl,
                );
            }
        }

        // Convert folders to Postman format
        foreach ($folders as $folderName => $requests) {
            $collection['item'][] = [
                'name' => $folderName,
                'item' => $requests,
            ];
        }

        return $collection;
    }

    /**
     * Build a single Postman request item.
     *
     * @param  array<string, mixed>  $endpoint
     * @return array<string, mixed>
     */
    private function buildRequest(
        string $method,
        string $path,
        array $endpoint,
        string $baseUrl,
    ): array {
        $summary =
            $endpoint['summary'] ??
            Str::title(
                str_replace(
                    ['/', '{', '}', '-', '_'],
                    [' ', '', '', ' ', ' '],
                    $path,
                ),
            );

        $request = [
            'name' => strtoupper($method).' '.$summary,
            'request' => [
                'method' => strtoupper($method),
                'header' => $this->buildHeaders($endpoint),
                'url' => $this->buildUrl($path, $endpoint),
            ],
            'response' => [],
        ];

        // Add description
        if (! empty($endpoint['description'])) {
            $request['request']['description'] = $endpoint['description'];
        }

        // Add auth if needed
        if (! empty($endpoint['security'])) {
            $request['request']['auth'] = [
                'type' => 'bearer',
                'bearer' => [
                    [
                        'key' => 'token',
                        'value' => '{{token}}',
                        'type' => 'string',
                    ],
                ],
            ];
        }

        // Add request body for POST/PUT/PATCH
        if (
            in_array(strtolower($method), ['post', 'put', 'patch']) &&
            ! empty($endpoint['parameters']['body'])
        ) {
            $body = $this->buildBody($endpoint['parameters']['body']);
            $request['request']['body'] = $body;

            if (($body['mode'] ?? '') === 'raw') {
                $request['request']['header'][] = [
                    'key' => 'Content-Type',
                    'value' => 'application/json',
                    'type' => 'text',
                ];
            }
        }

        return $request;
    }

    /**
     * Build request headers.
     *
     * @param  array<string, mixed>  $endpoint
     * @return array<int, array<string, mixed>>
     */
    private function buildHeaders(array $endpoint): array
    {
        $headers = [
            [
                'key' => 'Accept',
                'value' => 'application/json',
                'type' => 'text',
            ],
        ];

        return $headers;
    }

    /**
     * Build the Postman URL object.
     *
     * @param  array<string, mixed>  $endpoint
     * @return array<string, mixed>
     */
    private function buildUrl(string $path, array $endpoint): array
    {
        // Replace {param} with :param for Postman format
        $postmanPath = preg_replace("/\{(\w+)\}/", ':$1', $path);
        if ($postmanPath === null) {
            $postmanPath = $path;
        }

        $pathSegments = array_values(array_filter(explode('/', $postmanPath)));

        $url = [
            'raw' => '{{base_url}}'.$postmanPath,
            'host' => ['{{base_url}}'],
            'path' => $pathSegments,
        ];

        // Add path variables
        if (! empty($endpoint['parameters']['path'])) {
            $url['variable'] = array_map(
                fn ($p) => [
                    'key' => $p['name'],
                    'value' => $p['type'] === 'integer' ? '1' : 'value',
                    'description' => $p['description'] ?? '',
                ],
                $endpoint['parameters']['path'],
            );
        }

        // Add query parameters
        if (! empty($endpoint['parameters']['query'])) {
            $url['query'] = array_map(
                fn ($q) => [
                    'key' => $q['name'],
                    'value' => '',
                    'description' => $q['description'] ?? '',
                    'disabled' => false,
                ],
                $endpoint['parameters']['query'],
            );
        }

        return $url;
    }

    /**
     * Build the request body.
     *
     * @param  array<int, array<string, mixed>>  $fields
     * @return array<string, mixed>
     */
    private function buildBody(array $fields): array
    {
        $hasFile = collect($fields)->contains(fn ($f) => ! empty($f['is_file']));

        if ($hasFile) {
            return [
                'mode' => 'formdata',
                'formdata' => array_map(
                    fn ($f) => [
                        'key' => $f['name'] ?? 'file',
                        'value' => ! empty($f['is_file'])
                            ? ''
                            : $this->getExampleValue($f),
                        'type' => ! empty($f['is_file']) ? 'file' : 'text',
                        'description' => ($f['type'] ?? 'string').
                            (! empty($f['rules'])
                                ? ' | Rules: '.
                                    (is_array($f['rules'])
                                        ? implode(', ', $f['rules'])
                                        : $f['rules'])
                                : ''),
                    ],
                    $fields,
                ),
            ];
        }

        // JSON body
        $body = [];
        foreach ($fields as $field) {
            if (! empty($field['name'])) {
                $body[$field['name']] = $this->getExampleValue($field);
            }
        }

        return [
            'mode' => 'raw',
            'raw' => json_encode(
                $body,
                JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES,
            ),
            'options' => [
                'raw' => [
                    'language' => 'json',
                ],
            ],
        ];
    }

    /**
     * Get an example value for a field.
     *
     * @param  array<string, mixed>  $field
     */
    private function getExampleValue(array $field): mixed
    {
        $name = strtolower($field['name'] ?? '');
        $type = $field['type'] ?? 'string';

        if (! empty($field['enum'])) {
            return $field['enum'][0];
        }

        if (str_contains($name, 'email')) {
            return 'user@example.com';
        }
        if (str_contains($name, 'password')) {
            return 'password123';
        }
        if (str_contains($name, 'name')) {
            return 'John Doe';
        }
        if (str_contains($name, 'title')) {
            return 'Example Title';
        }
        if (
            str_contains($name, 'description') ||
            str_contains($name, 'content')
        ) {
            return 'This is a sample description.';
        }
        if (str_contains($name, 'slug')) {
            return 'example-slug';
        }
        if (str_contains($name, 'price') || str_contains($name, 'amount')) {
            return 99.99;
        }
        if (str_contains($name, '_id')) {
            return 1;
        }

        return match ($type) {
            'integer', 'int', 'bigint' => 1,
            'number', 'float', 'decimal' => 1.5,
            'boolean', 'bool' => true,
            'array' => ['item1', 'item2'],
            default => 'example_value',
        };
    }
}
